// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ooII-AZATDzJr3iD0vgh_4oiB8E-cNA',
    appId: '1:340042522532:web:acb321bd97a3c4d549ab31',
    messagingSenderId: '340042522532',
    projectId: 'icontrol-767a6',
    authDomain: 'icontrol-767a6.firebaseapp.com',
    databaseURL: 'https://icontrol-767a6-default-rtdb.firebaseio.com',
    storageBucket: 'icontrol-767a6.firebasestorage.app',
    measurementId: 'G-EQERJCKBX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDil8IFlINzhGPbq-fUxzYwxMkUOK3Qg',
    appId: '1:340042522532:android:d24fde1728122adc49ab31',
    messagingSenderId: '340042522532',
    projectId: 'icontrol-767a6',
    databaseURL: 'https://icontrol-767a6-default-rtdb.firebaseio.com',
    storageBucket: 'icontrol-767a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIkyhYSa7L5dxWtYatWo4dn41ybkuA8-c',
    appId: '1:340042522532:ios:9b8d704534d4f19049ab31',
    messagingSenderId: '340042522532',
    projectId: 'icontrol-767a6',
    databaseURL: 'https://icontrol-767a6-default-rtdb.firebaseio.com',
    storageBucket: 'icontrol-767a6.firebasestorage.app',
    iosBundleId: 'com.example.quickCart',
  );
}
